scope:hub:
  - changed-files:
      - any-glob-to-any-file: "apps/mcp-hub-worker/**"

scope:website:
  - changed-files:
      - any-glob-to-any-file: "apps/website/**"

scope:budget:
  - changed-files:
      - any-glob-to-any-file: "packages/tools-budget-buddy/**"

scope:schemas:
  - changed-files:
      - any-glob-to-any-file: "packages/mcp-schemas/**"

scope:registry:
  - changed-files:
      - any-glob-to-any-file: "packages/tool-registry/**"

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
      - any-glob-to-any-file: "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

infra:
  - changed-files:
      - any-glob-to-any-file: "infra/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "**/package.json"
      - any-glob-to-any-file: "package-lock.json"

# --- Area labels ---
area/product:
  - changed-files:
      - any-glob-to-any-file: "apps/mcp-hub-worker/**"
      - any-glob-to-any-file: "packages/**"

area/growth:
  - changed-files:
      - any-glob-to-any-file: "docs/marketing-comms.md"
      - any-glob-to-any-file: "docs/paid-media-plan.md"
      - any-glob-to-any-file: "docs/positioning-*.md"
      - any-glob-to-any-file: "docs/seo-keyword-map.md"

area/docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"

area/infra:
  - changed-files:
      - any-glob-to-any-file: "infra/**"
      - any-glob-to-any-file: ".github/workflows/**"

# --- Pricing/policy labels ---
pricing:
  - changed-files:
      - any-glob-to-any-file: "docs/pricing.md"
      - any-glob-to-any-file: "docs/policies/**"
      - any-glob-to-any-file: "docs/api/access-tiers.md"

public-api:
  - changed-files:
      - any-glob-to-any-file: "apps/mcp-hub-worker/src/**"
      - any-glob-to-any-file: "packages/mcp-schemas/**"

security:
  - changed-files:
      - any-glob-to-any-file: "docs/security.md"
      - any-glob-to-any-file: "SECURITY.md"
      - any-glob-to-any-file: "docs/policies/enterprise-sla.md"
