changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking"
    - title: "New Features"
      labels:
        - "feat"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "fix"
        - "bug"
    - title: "Pricing and Commercial"
      labels:
        - "pricing"
        - "decision"
    - title: "Enterprise"
      labels:
        - "customer-request"
        - "tier/enterprise"
    - title: "Documentation"
      labels:
        - "docs"
        - "documentation"
    - title: "Infrastructure"
      labels:
        - "ci"
        - "infra"
        - "chore"
    - title: "Dependencies"
      labels:
        - "dependencies"
    - title: "Other"
      labels:
        - "*"
  exclude:
    labels:
      - "skip-changelog"
