name: Epic
description: Multi-issue initiative spanning several tasks or milestones.
labels: ["epic"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template for initiatives that will be broken into multiple issues.

  - type: input
    id: title
    attributes:
      label: Epic title
      description: A concise name for this initiative.
    validations:
      required: true

  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What does this epic achieve when all child issues are done?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Product
        - GTM
        - Infrastructure
        - Docs
    validations:
      required: true

  - type: dropdown
    id: tier_impact
    attributes:
      label: Tier impact
      description: Which pricing tier(s) does this affect?
      multiple: true
      options:
        - Free
        - Growth
        - Enterprise
        - All tiers

  - type: textarea
    id: child_issues
    attributes:
      label: Child issues
      description: List the sub-tasks or link them as they are created.
      placeholder: |
        - [ ] #issue1
        - [ ] #issue2

  - type: textarea
    id: success_criteria
    attributes:
      label: Success criteria
      description: How do we know this epic is done?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (critical)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: true
