name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe the problem before the solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? Why is this needed?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about.
    validations:
      required: false

  - type: dropdown
    id: scope
    attributes:
      label: Affected area
      multiple: true
      options:
        - MCP Hub Worker
        - Website
        - Budget Buddy
        - Tool Registry
        - Schemas
        - Documentation
        - CI / Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, mockups, links, or anything else.
    validations:
      required: false
