name: Task
description: A small, scoped deliverable.
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Use this for focused, single-PR work items.

  - type: textarea
    id: description
    attributes:
      label: Task description
      description: What needs to be done?
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Product
        - GTM
        - Infrastructure
        - Docs
    validations:
      required: true

  - type: dropdown
    id: tier_impact
    attributes:
      label: Tier impact
      description: Which pricing tier(s) does this affect?
      multiple: true
      options:
        - Free
        - Growth
        - Enterprise
        - All tiers
        - None

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (critical)
        - P1 (high)
        - P2 (medium)
        - P3 (low)
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: When is this task done?
    validations:
      required: true

  - type: input
    id: parent_epic
    attributes:
      label: Parent epic
      description: Link to the parent epic issue if applicable.
      placeholder: "#issue-number"
